version: "3"
services:

  icecast2:
    build: 
      context: ./cadence_icecast2/ 
    image: kenellorando/cadence_icecast2
    container_name: icecast2
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./icecast2/config/cadence.xml:/etc/icecast2/cadence.xml
    networks:
      - external_services

  liquidsoap:
    build: 
      context: ./cadence_liquidsoap/ 
    image: kenellorando/cadence_liquidsoap
    container_name: liquidsoap
    restart: always
    volumes:
      - ./liquidsoap/config/cadence.liq:/etc/liquidsoap/cadence.liq
      - /music:/music
    depends_on:
      - icecast2
    expose:
      - 1234
    networks:
      internal_services:

  postgres:
    image: postgres:14.2-alpine
    container_name: postgres
    restart: always
    depends_on:
      - icecast2
    environment:
      POSTGRES_PASSWORD: hackme
    expose:
      - 5432
    networks:
      - internal_services

  cadence:
    build: 
      context: ./cadence/ 
    image: kenellorando/cadence
    container_name: cadence
    restart: always
    expose:
      - 1234
    ports:
      - 8080:8080
    env_file:
      - ./cadence/config/cadence.env
    volumes:
      - /music:/music
    depends_on:
      - icecast2
      - liquidsoap
      - postgres
    networks:
      internal_services:
      external_services:

networks:
  radio_services:
    driver: bridge
  metadata_services:
    driver: bridge